# -*- coding: utf-8 -*-
"""MNQ TOOL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17JrN-71aUQ-rqFb_0x_nwNwGgBjQACos
"""

from IPython.display import display, clear_output

# Widget per input dinamico
account_input = widgets.FloatText(value=50000, description='Fondi ($):', step=1000)
risk_input = widgets.FloatSlider(value=1, min=0.1, max=5, step=0.1, description='Rischio (%):')
stop_input = widgets.FloatText(value=30, description='Stop Loss (punti):', step=1)
point_value_input = widgets.FloatText(value=2, description='Valore punto ($):', step=0.1)
output_area = widgets.Output()

def calcola_contratti(_):
    with output_area:
        clear_output()
        capitale = account_input.value
        rischio_percentuale = risk_input.value
        stop_punti = stop_input.value
        valore_punto = point_value_input.value

        rischio_totale = capitale * (rischio_percentuale / 100)
        rischio_per_contratto = stop_punti * valore_punto
        contratti_massimi = int(rischio_totale // rischio_per_contratto)

        print(f"🧮 Rischio massimo per trade: ${rischio_totale:,.2f}")
        print(f"📉 Rischio per contratto: ${rischio_per_contratto:,.2f}")
        print(f"📊 Contratti massimi consigliati: {contratti_massimi}")

# Pulsante per calcolo
calcola_btn = widgets.Button(description="Calcola", button_style='success')
calcola_btn.on_click(calcola_contratti)

# Layout
app_layout = widgets.VBox([
    widgets.HTML(value="<h3>Calcolatore di Contratti per MNQ</h3>"),
    account_input,
    risk_input,
    stop_input,
    point_value_input,
    calcola_btn,
    output_area
])

display(app_layout)